-- reset.sql
-- Drops everything cleanly

DROP TABLE IF EXISTS RoomHasAmenity CASCADE;
DROP TABLE IF EXISTS Amenity CASCADE;
DROP TABLE IF EXISTS Renting CASCADE;
DROP TABLE IF EXISTS Booking CASCADE;
DROP TABLE IF EXISTS App_User CASCADE;
DROP TABLE IF EXISTS Archive_Renting CASCADE;
DROP TABLE IF EXISTS Archive_Booking CASCADE;
DROP TABLE IF EXISTS Room CASCADE;
DROP TABLE IF EXISTS Customer CASCADE;
DROP TABLE IF EXISTS Employee CASCADE;
DROP TABLE IF EXISTS Hotel CASCADE;
DROP TABLE IF EXISTS HotelChain_Phone CASCADE;
DROP TABLE IF EXISTS HotelChain_Email CASCADE;
DROP TABLE IF EXISTS HotelChain CASCADE;

-- Optional: reset sequences (Postgres usually handles this automatically with DROP)